<!DOCTYPE html>
<html>
<head>
	<title>Profile</title>
</head>
<body>
	<h1>Profile</h1>
	
	<form action="/profile/submit" method="post">
		<input type="input" name="name" placeholder="Name"><br>
		<input type="input" name="mob" placeholder="Month of birth">
		<input type="input" name="dob" placeholder="Day of birth">
		<input type="input" name="yob" placeholder="Year of birth"><br>
		<textarea name="bio" id="" cols="30" rows="10" placeholder="Biography"></textarea><br>

		<button type="submit">Submit</button>
	</form>

	
</body>
</html>