<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Profile Submited</title>
</head>
<body>
	<p>Hi <?= $name ?></p>
	<p>Your age is <?= $age ?></p>

    <?php if(date('m') == $mob && date('d') == $dob) { ?>
        Happy Birthday <?= $name ?>
    <?php } ?>

    <h3>Biography</h3>
	<p><?= $bio ?></p>

	<p><a href="/profile">Go home</a></p>
</body>
</html>